name: Living the Dream
favicon: null
layout_spectrum: 0.02482859487645328
typography_spectrum: 0.8092150615993887
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5934612376149744
  lightness: 0.5217252785805613
  saturation: 0.4318135096691549
  rhythmicContrast: 0.5816724738106132
purpose: []
