name: Living the Dream
favicon: null
layout_spectrum: 0.02482859487645328
typography_spectrum: 0.8092150615993887
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9298a6'
    - '#cacacc'
    - '#0c0805'
    - '#362c22'
    - '#61523d'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
